FROM node:22-alpine AS deps
WORKDIR /app
COPY frontend/package.json /app/package.json
RUN npm install
COPY frontend /app
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=deps /app/dist /usr/share/nginx/html
